Abarroteria_Cindy/Controllers/DetalleController.cs
using Abarroteria_Cindy.Data;
using Abarroteria_Cindy.Data.Entidades;
using Abarroteria_Cindy.Models;
using Mapster;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Diagnostics;

namespace Abarroteria_Cindy.Controllers
{
    public class DetalleController : Controller
    {
        private readonly ILogger<DetalleController> _logger;
        private AbarroteriaBdContext _context;

        public DetalleController(ILogger<DetalleController> logger, AbarroteriaBdContext context)
        {
            _logger = logger;
            _context = context;
        }
        public IActionResult Index()
       {
        var detalle = _context.Detalle_Factura.Where(w => w.Eliminado == false).ProjectToType<DetalleVm>().ToList();
            return View(detalle);
        }





        [HttpGet]
        public IActionResult Insertar(Guid encabezadoId)
        {
            ViewBag.EncabezadoId = encabezadoId;

            var productos = _context.Producto.Select(p => new {
                Id_Producto = p.Id_Producto,
                Nombre = p.Nombre,
                Precio_Normal = p.Precio_Normal,
                Precio_Mayorista = p.Precio_Mayorista
            }).ToList();

            ViewBag.Productos = productos;

            return View();
        }

        [HttpPost]

        public IActionResult Insertar(DetalleVm detalle)
        {
            

            Console.WriteLine("El ID del producto es___________--------: " + detalle.Id_Producto);
            Console.WriteLine(detalle.Id_Producto);


            // Validar si el encabezado existe
            var encabezado = _context.Encabezado_Factura.FirstOrDefault(e => e.Id_Encabezado_factura == detalle.Id_Encabezado_Factura);
            if (encabezado == null)
            {
                return NotFound("No se encontró el encabezado de factura asociado.");
            }

            // Validar si el producto existe
            var producto = _context.Producto.FirstOrDefault(p => p.Id_Producto == detalle.Id_Producto);
            if (producto == null)
            {
                return NotFound("No se encontró el producto asociado.");
            }

            // Obtener el precio del producto
            var precio = producto.Precio_Normal;

            // Calcular el total de línea
            var totalLinea = detalle.Cantidad * precio;

            // Crear el nuevo detalle de factura
            var nuevoDetalle = new Detalle_Factura
            {
                Id_Detalle_Factura = Guid.NewGuid(),
                Cantidad = detalle.Cantidad,
                
                Total_Linea = totalLinea,
                Id_Encabezado_Factura = detalle.Id_Encabezado_Factura,
                Id_Producto = detalle.Id_Producto
                


             
            };
           

            // Agregar el nuevo detalle al contexto y guardar los cambios en la base de datos
            _context.Detalle_Factura.Add(nuevoDetalle);
            _context.SaveChanges();

            

            TempData["mensaje"] = "Registrado Correctamente";

            // Redirigir al método de pago con el ID del encabezado
            return RedirectToAction("Insertar", new { encabezadoId = detalle.Id_Encabezado_Factura });
        }

        [HttpGet]
        public IActionResult ConfirmarDetalle(Guid encabezadoId)
        {
            var detalles = _context.Detalle_Factura
                .Include(d => d.Producto) // Incluir la entidad Producto
                .Where(d => d.Id_Encabezado_Factura == encabezadoId && !d.Eliminado)
                .Select(d => new DetalleVm
                {
                    Id_Detalle_Factura = d.Id_Detalle_Factura,
                    Cantidad = d.Cantidad,
                    Producto = new ProductoVm // pa que se muestre los nombres y precios de productos
                    {
                        Id_Producto = d.Producto.Id_Producto,
                        Nombre = d.Producto.Nombre,
                        Precio_Normal = d.Producto.Precio_Normal,
                        Precio_Mayorista = d.Producto.Precio_Mayorista
                    },
                    Total_Linea = d.Cantidad > 12 ? d.Producto.Precio_Mayorista * d.Cantidad : d.Producto.Precio_Normal * d.Cantidad,
                    Id_Encabezado_Factura = d.Id_Encabezado_Factura,
                    Id_Producto = d.Id_Producto,
                })
                .ToList();

            ViewBag.EncabezadoId = encabezadoId;
            return View(detalles);
        }



        [HttpGet]
        public IActionResult Editar(Guid Id)
        {
            var detalle = _context.Detalle_Factura.FirstOrDefault(d => d.Id_Detalle_Factura == Id);
            if (detalle == null)
            {
                return NotFound("No se encontró el detalle de factura.");
            }

            // Obtener la lista de productos y convertirla a una lista de SelectListItem
            var productos = _context.Producto.Select(p => new SelectListItem
            {
                Value = p.Id_Producto.ToString(),
                Text = p.Nombre
            }).ToList();

            // Mapear el detalle a un ViewModel si es necesario
            var detalleVm = detalle.Adapt<DetalleVm>();

            // Asignar la lista de productos al ViewBag
            ViewBag.Productos = productos;

            // Cargar datos adicionales necesarios para la vista
            ViewBag.EncabezadoId = detalle.Id_Encabezado_Factura;

            return View(detalleVm);
        }

        [HttpPost]
        public IActionResult Editar(DetalleVm detalleVm)
        {
            var detalle = _context.Detalle_Factura.FirstOrDefault(d => d.Id_Detalle_Factura == detalleVm.Id_Detalle_Factura);
            if (detalle == null)
            {
                return NotFound("No se encontró el detalle de factura.");
            }

            // Actualizar los campos del detalle con los valores del ViewModel
            detalle.Cantidad = detalleVm.Cantidad;
            detalle.Id_Producto = detalleVm.Id_Producto;

            // Guardar los cambios en la base de datos
            _context.SaveChanges();

            TempData["mensaje"] = "Detalle actualizado correctamente.";

            // Redirigir a la acción ConfirmarDetalle con el ID del encabezado
            return RedirectToAction("ConfirmarDetalle", new { encabezadoId = detalle.Id_Encabezado_Factura });
        }




        [HttpPost]
        public IActionResult Eliminar(Guid id)
        {
            var detalle = _context.Detalle_Factura.FirstOrDefault(d => d.Id_Detalle_Factura == id);
            Guid encabezadoId = Guid.Empty;

            if (detalle != null)
            {
                encabezadoId = detalle.Id_Encabezado_Factura; // Almacenar el ID del encabezado antes de eliminar el detalle
                _context.Detalle_Factura.Remove(detalle);
                _context.SaveChanges();
                TempData["mensaje"] = "Detalle eliminado correctamente.";
                TempData["encabezadoId"] = encabezadoId; // Almacenar el ID del encabezado en TempData
            }

            return RedirectToAction("ConfirmarDetalle", new { encabezadoId = encabezadoId });
        }

        [HttpPost]
        public IActionResult Continuar(Guid encabezadoId)
        {
            // Redirigir al método ConfirmarDetalle con el ID del encabezado
            return RedirectToAction("ConfirmarDetalle", new { encabezadoId = encabezadoId });
        }
       
    }
}

Abarroteria_Cindy/Controllers/PagoController.cs
using Abarroteria_Cindy.Data;
using Abarroteria_Cindy.Data.Entidades;
using Abarroteria_Cindy.Models;
using Mapster;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System;

namespace Abarroteria_Cindy.Controllers
{
    public class PagoController : Controller
    {
        private readonly ILogger<PagoController> _logger;
        private AbarroteriaBdContext _context;

        public PagoController(ILogger<PagoController> logger, AbarroteriaBdContext context)
        {
            _logger = logger;
            _context = context;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var pagos = _context.Pago.Where(p => !p.Eliminado).ProjectToType<PagoVm>().ToList();
            return View(pagos);
        }

        [HttpGet]
        public IActionResult Insertar(Guid encabezadoId)
        {
            var encabezado = _context.Encabezado_Factura
                .Include(e => e.Detalles)
                .FirstOrDefault(e => e.Id_Encabezado_factura == encabezadoId);

            if (encabezado == null)
            {
                return RedirectToAction("Index", "Encabezado_");
            }

            var pagoVm = new PagoVm
            {
                Id_Encabezado_factura = encabezadoId,
                TotalPagar = encabezado.Detalles.Sum(detalle => detalle.Total_Linea),
                Impuesto = encabezado.Detalles.Sum(detalle => detalle.Total_Linea) * 0.15,
                Detalles = encabezado.Detalles.ToList()
            };

            return View(pagoVm);
        }

        [HttpPost]
        public IActionResult Insertar(PagoVm pagoVm)
        {
           
                var encabezado = _context.Encabezado_Factura
                    .Include(e => e.Detalles)
                    .FirstOrDefault(e => e.Id_Encabezado_factura == pagoVm.Id_Encabezado_factura);

                if (encabezado == null)
                {
                    return RedirectToAction("Index", "Encabezado_");
                }

                var totalPagar = encabezado.Detalles.Sum(detalle => detalle.Total_Linea);
                var impuesto = totalPagar * 0.15;
                var totalimp = totalPagar + impuesto;

                if (pagoVm.MontoRecibido < totalimp)
                {
                    ModelState.AddModelError("MontoRecibido", "El monto recibido debe ser mayor o igual al total a pagar más impuesto.");
                    return View(pagoVm);
                }

                var cambio = pagoVm.MontoRecibido - totalimp;

                var pago = new Pago
                {
                    Id = Guid.NewGuid(),
                    Impuesto = impuesto,
                    TotalPagar = totalPagar,
                    MontoRecibido = pagoVm.MontoRecibido,
                    Cambio = cambio,
                    TotalImp = totalimp,
                    Id_Encabezado_Factura = encabezado.Id_Encabezado_factura,
                    NumeroFactura = encabezado.NumeroFactura,
                    CreatedBy = pagoVm.CreatedBy,
                    CreatedDate = DateTime.Now,
                    Eliminado = pagoVm.Eliminado
                };

                // Asignar los valores de impuesto, total más impuesto y cambio al objeto pagoVm
                pagoVm.Impuesto = impuesto;
                pagoVm.TotalImp = totalimp;
                pagoVm.Cambio = cambio;


                _context.Pago.Add(pago);
                _context.SaveChanges();

                TempData["mensaje"] = "Pago registrado correctamente.";

                return RedirectToAction("Index", "Encabezado_", new { encabezadoId = pagoVm.Id_Encabezado_factura });
            }

        

    }
}

Abarroteria_Cindy/Views/Detalle/ConfirmarDetalle.cshtml
@model List<DetalleVm>
@{
    ViewData["Title"] = "ConfirmarDetalle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Confirmar Detalle</h1>

<div class="modal fade" id="confirmarDetalleModal" tabindex="-1" role="dialog" aria-labelledby="confirmarDetalleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="confirmarDetalleModalLabel">Confirmar Detalle</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close" id="cerrarModal">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Producto</th>
                            <th>Cantidad</th>
                            <th>Precio Unitario</th>
                            <th>Total</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var detalle in Model)
                        {
                            <tr>
                                <td>@(detalle.Producto != null ? detalle.Producto.Nombre : "")</td>
                                <td>@detalle.Cantidad</td>
                                <td>@(detalle.Producto != null && detalle.Cantidad > 12 ? detalle.Producto.Precio_Mayorista.ToString() : detalle.Producto != null ? detalle.Producto.Precio_Normal.ToString() : "")</td>
                                <td>@detalle.Total_Linea</td>
                                <td>

                                    <div class="btn-group" role="group" aria-label="Acciones">
                                        <div class="btn-group" role="group" aria-label="Acciones">
                                            <form method="post" action="@Url.Action("Eliminar", "Detalle", new { id = detalle.Id_Detalle_Factura })">
                                                <button type="submit" class="btn btn-danger">Eliminar</button>
                                            </form>
                                        <a href="@Url.Action("Editar", "Detalle", new { id = detalle.Id_Detalle_Factura })" class="btn btn-primary">Editar</a>
                                        
                                    </div>
                                </td>
                            </tr>



                        }
                    </tbody>
                </table>
            </div>
            <div class="modal-footer">
                

                <a href="@Url.Action("Insertar", "Pago", new { encabezadoId = ViewBag.EncabezadoId })" class="btn btn-success">Continuar al Pago</a>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $(function () {
            $('#confirmarDetalleModal').modal('show');

            
            $('#cerrarModal').click(function () {
                window.location.href = '@Url.Action("Insertar", "Detalle", new { encabezadoId = ViewBag.EncabezadoId })';
            });

            $('#Editar').click(function () {
                $('#confirmarDetalleModal').modal('hide');
              
                window.location.href = '@Url.Action("ConfirmarDetalle", "Detalle")?encabezadoId=@ViewBag.EncabezadoId';
            });
        });
    </script>
}

Abarroteria_Cindy/Views/Detalle/Editar.cshtml
@model DetalleVm
@{
    ViewData["Title"] = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Editar Detalle</h1>
<div class="container">
    <div class="row">
        <form asp-action="Editar" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id_Detalle_Factura" />
            <input type="hidden" asp-for="Id_Encabezado_Factura" />
            <div class="form-group">
                <label asp-for="Cantidad" class="control-label"></label>
                <input asp-for="Cantidad" class="form-control" />
                <span asp-validation-for="Cantidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Id_Producto" class="control-label"></label>
                <select asp-for="Id_Producto" class="form-control" asp-items="ViewBag.Productos"></select>
                <span asp-validation-for="Id_Producto" class="text-danger"></span>
            </div>

            <div class="form-group">
                <div class="form-group">
                    <input type="submit" value="Agregar Producto" class="btn btn-primary" id="btnAgregarProducto" />
                </div>
                <a href="javascript:history.back()" class="btn btn-secondary">Cancelar</a>
            </div>
        </form>
    </div>
</div>

Abarroteria_Cindy/Views/Detalle/Eliminar.cshtml
@model DetalleVm
@{
    ViewData["Title"] = "Eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Eliminar</h1>
<div class="row">
    <form method="post" asp-action="Eliminar">
        <div class="row">
            <div class="danger">
                @if (TempData["mensaje"] != null)
                {
                    <div class="alert alert-warning alert-dismissible" role="alert">
                        <p> @TempData["mensaje"]</p>
                        <button type="button" class="close" data-dismiss="alert" aria-label="close">
                            <span aria-hidden="true">&times;</span>

                        </button>
                    </div>
                }
            </div>


        <div class="col-md-12">
            <p>¿Estás seguro de que deseas eliminar el detalle seleccionado?</p>
            <dl class="dl-horizontal">
                <dt>Producto:</dt>
                <dd>@Model.Producto.Nombre</dd>
                <dt>Cantidad:</dt>
                <dd>@Model.Cantidad</dd>
                <dt>Total de Línea:</dt>
                <dd>@Model.Total_Linea</dd>
            </dl>
            
                <button type="submit" class="btn btn-danger">Eliminar</button>
                <a href="@Url.Action("ConfirmarDetalle", "Detalle", new { encabezadoId = TempData["encabezadoId"] })" class="btn btn-primary">Cancelar</a>
            </form>
        </div>
    </div>
</div>

Abarroteria_Cindy/Views/Detalle/Index.cshtml
@model List<DetalleVm>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h3>Index</h3>
<form asp-action="Insertar" method="get">
    <div class=" = " row">
        <div class="danger">
            @if (TempData["mensaje"] != null)
            {
                <div class="alert alert-warning alert-dismissable" role="alert">
                    <p> @TempData["mensaje"]</p>
                    <button type="button" class="close" data-dismiss="alert" aria-label="close">

                        <span aria-hidden="true">&times;</span>
                    </button>

                </div>
            }
        </div>
    </div>
    <div class="form-group">

        <input type="submit" value="Nuevo Registro" class="btn-success" style="color: #000; background-color: #0dcaf0; border-color: #0dcaf0;">

    </div>

    @if (Model.Count > 0)
    {
        <div class="ScrollB">
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Producto</th>
                        <th>Cantidad</th>
                        <th>Precio</th>
                        <th>Total_Linea</th>
                        <th>Acciones</th>
                        
                        
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Producto.Nombre</td>
                            <td>@item.Cantidad</td>
                            <td>@item.Producto.Precio_Normal</td>
                            <td>@item.Total_Linea</td>
                            
                            
                            <td>
                                @Html.ActionLink("Editar", "Editar", "Detalle", new { @Id_Detalle_Factura = item.Id_Detalle_Factura }, new { @class = "btn btn-info" })
                                @Html.ActionLink("Eliminar", "Eliminar", "Detalle", new { @Id_Detalle_Factura = item.Id_Detalle_Factura }, new { @class = "btn btn-info" })
                            </td>

                        </tr>
                    }
                </tbody>


            </table>

        </div>
    }


</form>

Abarroteria_Cindy/Views/Detalle/Insertar.cshtml
@model DetalleVm
@{
    ViewData["Title"] = "Insertar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>Agregar Nuevo Detalle de Factura</h2>

<div class="container">
    <div class="row">
        <form method="post" asp-action="Insertar">
            <div class="row">
                <div class="danger">
                    @if (TempData["mensaje"] != null)
                    {
                        <div class="alert alert-warning alert-dismissible" role="alert">
                            <p> @TempData["mensaje"]</p>
                            <button type="button" class="close" data-dismiss="alert" aria-label="close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    }
                </div>
            </div>

            <input type="hidden" name="Id_Encabezado_Factura" value="@ViewBag.EncabezadoId" />

            <div class="form-group">
                <label for="Id_Producto">Producto:</label>
                <select class="form-control" id="Id_Producto" name="Id_Producto">
                    <option value="">-- Seleccione un Producto --</option>
                    @foreach (var producto in ViewBag.Productos)
                    {
                        <option value="@producto.Id_Producto"
                                data-precio-normal="@producto.Precio_Normal"
                                data-precio-mayorista="@producto.Precio_Mayorista">
                            @producto.Nombre
                        </option>
                    }
                </select>
            </div>

            <div class="form-group">
                <label for="Precio">Precio:</label>
                <input type="text" class="form-control" id="Precio" readonly />
            </div>

            <div class="form-group">
                <label for="Cantidad">Cantidad:</label>
                <input type="number" class="form-control" id="Cantidad" name="Cantidad" />
            </div>

            <div class="form-group">
                <label for="Total_Linea">Total de Línea:</label>
                <input type="text" class="form-control" id="Total_Linea" readonly />
            </div>

            <div class="form-group">
                <div class="btn-group" role="group" aria-label="Botones de acción">
                    <a href="@Url.Action("ConfirmarDetalle", "Detalle", new { encabezadoId = ViewBag.EncabezadoId })" class="btn btn-primary">Confirmar Detalle</a>
                    <input type="submit" value="Agregar Producto" class="btn btn-primary" id="btnAgregarProducto" />
                    
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            $('#Id_Producto, #Cantidad').change(function () {
                var productId = $('#Id_Producto').val();
                var quantity = $('#Cantidad').val();
                var price = $('#Id_Producto option:selected').data('precio-normal');
                if (parseInt(quantity) > 12) {
                    price = $('#Id_Producto option:selected').data('precio-mayorista');
                }
                if (!isNaN(price) && !isNaN(quantity)) {
                    var totalLinea = price * quantity;
                    $('#Precio').val(price);
                    $('#Total_Linea').val(totalLinea);
                }
            });
        });
    </script>
}