Abarroteria_Cindy/Models/Domain/Abarroteria_Cindy/Proveedor.cs
using System;
using System.Collections.Generic;

namespace Abarroteria_Cindy.Models.Domain.Abarroteria_Cindy
{
    public partial class Proveedor
    {
        public Proveedor()
        {
            Inventarios = new HashSet<Inventario>();
        }

        public Guid IdProveedor { get; set; }
        public string Nombre { get; set; } = null!;
        public int Telefono { get; set; }
        public string Correo { get; set; } = null!;
        public string Direccion { get; set; } = null!;
        public Guid CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public bool Eliminado { get; set; }

        public virtual ICollection<Inventario> Inventarios { get; set; }
    }
}

Abarroteria_Cindy/Controllers/ProveedorController.cs
using Abarroteria_Cindy.Data.Entidades;
using Abarroteria_Cindy.Data;
using Abarroteria_Cindy.Models;
using Microsoft.AspNetCore.Mvc;
using Mapster;
using Abarroteria_Cindy.Filters;
using Newtonsoft.Json;

namespace Abarroteria_Cindy.Controllers
{
    public class ProveedorController : Controller
    {
        private readonly ILogger<ProveedorController> _logger;
        private readonly AbarroteriaBdContext _context;

        public ProveedorController(ILogger<ProveedorController> logger, AbarroteriaBdContext context)
        {
            _logger = logger;
            _context = context;
        }
        [ClaimRequirement("Proveedores")]
        public IActionResult Index()
        {
            var proveedor = _context.Proveedor.Where(w => w.Eliminado == false).ProjectToType<ProveedorVm>().ToList();
            return View(proveedor);
        }

        [HttpGet]
        [ClaimRequirement("Proveedores")]
        public IActionResult Insertar()
        {
            var proveedor = new ProveedorVm();
            return View(proveedor);
        }

        [HttpPost]
        [ClaimRequirement("Proveedores")]
        public IActionResult Insertar(ProveedorVm proveedor)
        {
            if (!ModelState.IsValid)
            {
                TempData["mensaje"] = "Todos los campos son obligatorios y deben ser válidos.";
                return View(proveedor);
            }
            var sesionJson = HttpContext.Session.GetString("UsuarioObjeto");
            var base64EncodedBytes = System.Convert.FromBase64String(sesionJson);
            var sesion = System.Text.Encoding.UTF8.GetString(base64EncodedBytes);
            EmpleadoVm UsuarioObjeto = JsonConvert.DeserializeObject<EmpleadoVm>(sesion);
            var nuevoProveedor = new Proveedor
            {
                Id_Proveedor = Guid.NewGuid(),
                Nombre = proveedor.Nombre,
                Telefono = proveedor.Telefono,
                Correo = proveedor.Correo,
                Direccion = proveedor.Direccion,
                CreatedBy = UsuarioObjeto.Id_Empleado, // Debes establecer el valor correcto para CreatedBy
                CreatedDate = DateTime.Now, // Debes establecer el valor correcto para CreatedDate
                Eliminado = false // Por defecto, no está eliminado
            };

            _context.Proveedor.Add(nuevoProveedor);
            _context.SaveChanges();
            TempData["mensaje"] = "Proveedor registrado correctamente.";
            return RedirectToAction("Index");
        }

        [HttpGet]
        [ClaimRequirement("Proveedores")]
        public IActionResult Editar(Guid Id_Proveedor)
        {
            var registro = _context.Proveedor
                                  .Where(w => w.Id_Proveedor == Id_Proveedor)
                                  .ProjectToType<ProveedorVm>()
                                  .FirstOrDefault();

            return View(registro);
        }

        [HttpPost]
        [ClaimRequirement("Proveedores")]
        public IActionResult Editar(ProveedorVm proveedor)
        {
            
            var nuevoproveedor = _context.Proveedor.FirstOrDefault(w => w.Id_Proveedor == proveedor.Id_Proveedor);


            nuevoproveedor.Nombre = proveedor.Nombre;
            nuevoproveedor.Telefono = proveedor.Telefono;
            nuevoproveedor.Correo = proveedor.Correo;
            nuevoproveedor.Direccion = proveedor.Direccion;

            _context.SaveChanges();
            TempData["mensaje"] = "Modificado Correctamente";

            return RedirectToAction("Index");
        }

        [HttpGet]
        [ClaimRequirement("Proveedores")]
        public IActionResult Eliminar(Guid Id_Proveedor)
        {

            var registro = _context.Proveedor
                                 .Where(w => w.Id_Proveedor == Id_Proveedor)
                                 .ProjectToType<ProveedorVm>()
                                 .FirstOrDefault();

            return View(registro);
        }
        [HttpPost]
        [ClaimRequirement("Proveedores")]
        public IActionResult Eliminar(ProveedorVm registros)
        {

            var nuevoregistro = _context.Proveedor.Where(w => w.Id_Proveedor == registros.Id_Proveedor).FirstOrDefault();
            nuevoregistro.Eliminado = true;
            _context.SaveChanges();
            TempData["mensaje"] = "El registro fue eliminado Correctamente";

            return RedirectToAction("Index");
        }
    }
}

Abarroteria_Cindy/Views/Proveedor/Editar.cshtml
@model ProveedorVm
@{
    ViewData["Title"] = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <h1 style="text-align: center;">Editar Proveedor</h1>

    <div class="row">
        <form method="post" asp-action="Editar">
            <div class="row">
                <div class="danger">
                    @if (TempData["mensaje"] != null)
                    {
                        <div class="alert alert-warning alert-dismissible" role="alert">
                            <p> @TempData["mensaje"]</p>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    }
                </div>
            </div>

            <input asp-for="Id_Proveedor" type="hidden" class="form-control" />

            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Telefono" class="control-label"></label>
                <input asp-for="Telefono" class="form-control" />
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Correo" class="control-label"></label>
                <input asp-for="Correo" class="form-control" />
                <span asp-validation-for="Correo" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Direccion" class="control-label"></label>
                <input asp-for="Direccion" class="form-control" />
                <span asp-validation-for="Direccion" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Editar" class="btn btn-success " style="color: #000; background-color: #0dcaf0; border-color: #0dcaf0;" />
            </div>
        </form>
    </div>
</div>

Abarroteria_Cindy/Views/Proveedor/Eliminar.cshtml
@model ProveedorVm
@{
    ViewData["Title"] = "Eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <h1 style="text-align: center;">Eliminar Proveedor</h1>

    <div class="row">
        <form method="post" asp-action="Eliminar">
            <div class="row">
                <div class="col-md-12">
                    @if (TempData["mensaje"] != null)
                    {
                        <div class="alert alert-warning alert-dismissible" role="alert">
                            <p> @TempData["mensaje"]</p>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    }
                </div>
            </div>

            <input asp-for="Id_Proveedor" type="hidden" class="form-control" />

            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" readonly />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Telefono" class="control-label"></label>
                <input asp-for="Telefono" class="form-control" readonly />
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Correo" class="control-label"></label>
                <input asp-for="Correo" class="form-control" readonly />
                <span asp-validation-for="Correo" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Direccion" class="control-label"></label>
                <input asp-for="Direccion" class="form-control" readonly />
                <span asp-validation-for="Direccion" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Eliminar" class="btn btn-success " style="color: #000; background-color: #0dcaf0; border-color: #0dcaf0;" />
            </div>
        </form>
    </div>
</div>

Abarroteria_Cindy/Views/Proveedor/Index.cshtml
@model List<ProveedorVm>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form asp-action="Insertar" method="get">
    <h1 style="text-align: center;">Proveedores</h1>
    <div class="row">
        <div class="col-md-12">
            @if (TempData["mensaje"] != null)
            {
                <div class="alert alert-warning alert-dismissable" role="alert">
                    <p> @TempData["mensaje"]</p>
                    <button type="button" class="close" data-dismiss="alert" aria-label="close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            }
        </div>
    </div>
    <div class="form-group">
        <input type="submit" value="Nuevo Registro" class="btn btn-success" style="color: #000; background-color: #0dcaf0; border-color: #0dcaf0;">
    </div>
</form>

@if (Model.Count > 0)
{
    <div class="table-responsive">
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Teléfono</th>
                    <th>Correo</th>
                    <th>Dirección</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Nombre</td>
                        <td>@item.Telefono</td>
                        <td>@item.Correo</td>
                        <td>@item.Direccion</td>
                        <td>
                            @Html.ActionLink("Editar", "Editar", "Proveedor", new { @Id_Proveedor = item.Id_Proveedor }, new { @class = "btn btn-info" })
                            @Html.ActionLink("Eliminar", "Eliminar", "Proveedor", new { @Id_Proveedor = item.Id_Proveedor }, new { @class = "btn btn-info" })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}

Abarroteria_Cindy/Views/Proveedor/Insertar.cshtml
@model ProveedorVm
@{
    ViewData["Title"] = "Insertar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <h1 style="text-align: center;">Nuevo Proveedor</h1>

    <div class="row">
        <form method="post" asp-action="Insertar">
            <div class="row">
                <div class="col-md-12">
                    @if (TempData["mensaje"] != null)
                    {
                        <div class="alert alert-warning alert-dismissible" role="alert">
                            <p> @TempData["mensaje"]</p>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    }
                </div>
            </div>

            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Telefono" class="control-label"></label>
                <input asp-for="Telefono" class="form-control" />
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Correo" class="control-label"></label>
                <input asp-for="Correo" class="form-control" />
                <span asp-validation-for="Correo" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Direccion" class="control-label"></label>
                <input asp-for="Direccion" class="form-control" />
                <span asp-validation-for="Direccion" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Agregar" class="btn btn-success style="background-color: #94D3F6; color: black;" />
            </div>
        </form>
    </div>
</div>